In [1]:
import pandas as pd

## Fine-Tuning ViT for Chest X-Ray Diagnosis

In [3]:
data_entry = pd.read_csv("Data_Entry_2017.csv")

In [4]:
data_entry.head()

,Image Index,Finding Labels,Follow-up #,Patient ID,Patient Age,Patient Gender,View Position,OriginalImage[Width,Height],OriginalImagePixelSpacing[x,y],Unnamed: 11
0,00000001_000.png,Cardiomegaly,0,1,058Y,M,PA,2682,2749,0.143,0.143,NaN
1,00000001_001.png,Cardiomegaly|Emphysema,1,1,058Y,M,PA,2894,2729,0.143,0.143,NaN
2,00000001_002.png,Cardiomegaly|Effusion,2,1,058Y,M,PA,2500,2048,0.168,0.168,NaN
3,00000002_000.png,No Finding,0,2,081Y,M,PA,2500,2048,0.171,0.171,NaN
4,00000003_000.png,Hernia,0,3,081Y,F,PA,2582,2991,0.143,0.143,NaN

In [9]:
data_entry["Finding Labels"].str.split('|').explode().unique()

array(['Cardiomegaly', 'Emphysema', 'Effusion', 'No Finding', 'Hernia',
       'Infiltration', 'Mass', 'Nodule', 'Atelectasis', 'Pneumothorax',
       'Pleural_Thickening', 'Pneumonia', 'Fibrosis', 'Edema',
       'Consolidation'], dtype=object)

In [10]:
unique_labels = data_entry["Finding Labels"].str.split('|').explode().unique()

In [11]:
diseases = [l for l in unique_labels if l != 'No Finding']

In [14]:
len(diseases)

14

In [16]:
#encoding labels
for label in diseases:
    data_entry[label] = data_entry['Finding Labels'].str.contains(label, regex = False).astype(int)

In [18]:
count_classes = data_entry[diseases].sum().sort_values(ascending = False)

In [20]:
(count_classes / len(data_entry) * 100).sort_values(ascending = False)

Infiltration          17.722083
Effusion              11.868534
Atelectasis           10.288084
Nodule                 5.639493
Mass                   5.124866
Pneumothorax           4.725294
Consolidation          4.162504
Pleural_Thickening     3.019087
Cardiomegaly           2.472351
Emphysema              2.244024
Edema                  2.054049
Fibrosis               1.503746
Pneumonia              1.206743
Hernia                 0.202462
dtype: float64

In [26]:
(((data_entry['Finding Labels'] == 'No Finding').sum()) /  len(data_entry)) * 100

np.float64(53.88155547627542)

In [27]:
healthy_patients = data_entry[data_entry['Finding Labels'] == 'No Finding']

In [28]:
healthy_patients.head()

,Image Index,Finding Labels,Follow-up #,Patient ID,Patient Age,Patient Gender,View Position,OriginalImage[Width,Height],OriginalImagePixelSpacing[x,...,Infiltration,Mass,Nodule,Atelectasis,Pneumothorax,Pleural_Thickening,Pneumonia,Fibrosis,Edema,Consolidation
3,00000002_000.png,No Finding,0,2,081Y,M,PA,2500,2048,0.171,...,0,0,0,0,0,0,0,0,0,0
13,00000005_000.png,No Finding,0,5,069Y,F,PA,2048,2500,0.168,...,0,0,0,0,0,0,0,0,0,0
14,00000005_001.png,No Finding,1,5,069Y,F,AP,2500,2048,0.168,...,0,0,0,0,0,0,0,0,0,0
15,00000005_002.png,No Finding,2,5,069Y,F,AP,2500,2048,0.168,...,0,0,0,0,0,0,0,0,0,0
16,00000005_003.png,No Finding,3,5,069Y,F,PA,2992,2991,0.143,...,0,0,0,0,0,0,0,0,0,0

In [31]:
print(data_entry[data_entry['Finding Labels'].str.contains('|', regex=False)]['Finding Labels'].head(10))

1                                Cardiomegaly|Emphysema
2                                 Cardiomegaly|Effusion
7                                   Hernia|Infiltration
12                                          Mass|Nodule
20                                Effusion|Infiltration
37                                        Effusion|Mass
39                               Emphysema|Pneumothorax
40                               Emphysema|Pneumothorax
42         Effusion|Emphysema|Infiltration|Pneumothorax
43    Emphysema|Infiltration|Pleural_Thickening|Pneu...
Name: Finding Labels, dtype: object